title: White Hat Desert Rally 2023
email: security [@] whitehatdesert[.]com
description: >- # this means to ignore newlines until "baseurl:"
  White Hat Desert Rally 2023
  Doha
  Qatar
domain: whitehatdesert.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://whitehatdesert.com  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /      # place folder name if the site is served in a subfolder
encoding: UTF-8

theme: minima

